name:                exercitium2
version:             0.1.0.0
github:              "chemacortes/exercitium2"
license:             BSD3
author:              "Chema Cortés"
maintainer:          "dev.xtrem@gmail.com"
copyright:           "2022 Chema Cortés"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chemacortes/exercitium2#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  exercitium2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercitium2

tests:
  exercitium2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercitium2
